################################################################################
#
#  Provisions Org Custom Conformance Packs
# 
# @kmmahaj
#
# License:
# This code is made available under the MIT-0 license. See the LICENSE file.
################################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: Provisions Org Custom Conformance Packs(qs-1t0eilb5g)

Parameters:

  DeliveryS3Bucket:
    Description: The name of the Amazon S3 bucket where AWS Config stores conformance pack templates.
    Type: String
    Default: 'awsconfigconforms-orgbucket'

  OrganizationConformancePackName:
    Description: Name of the custom config conformance pack
    Type: String
    Default: 'aws-pcicustomconfpack-remediations-org'

  TemplateS3Uri:
    Description: Location of S3 file containing the conformance pack template body. Points to the conformance pack template
    Type: String
    Default: 's3://s3-pci-confpack-org/aws-pci-conformancepack-remediations-v1.yml'

Resources:

  OrganizationConformancePack:
    Type: 'AWS::Config::OrganizationConformancePack'
    Properties: 
      OrganizationConformancePackName: !Ref OrganizationConformancePackName
      DeliveryS3Bucket: !Ref DeliveryS3Bucket
      ExcludedAccounts:
        - "798653331051"
        - "652691327122"
        - "227214716926"
        - "018299706242"
        - "525354019754"
        - "602116679243"
        - "187355837323"
        - "341476298946"
        - "221809298128"
        - "388407216922"
      TemplateS3Uri: !Ref TemplateS3Uri
    